language: go

go:
  - 1.5.1
  - tip
env:
  - GOARCH=amd64

install:
  - go get github.com/tools/godep
  - go get github.com/stretchr/testify

script:
  - godep restore
  - go test ./...

notifications:
  email:
    on_success: change
    on_failure: always
